version: '3.8'
services:
 
  backend:
    container_name: admin_api
    build: 
      context: .
      dockerfile: Dockerfile
    environment: 
      DB_HOST: db
      DB_DATABASE: admin
      DB_USER: root
      DB_PASSWORD: abc
    ports: 
    - 8000:8000
    volumes:
    - .:/app
    depends_on: 
    - db
    networks:
    - app
  
  db:
    container_name: admin_db
    image: mysql:5.7.22
    environment: 
      MYSQL_DATABASE: admin
      MYSQL_USER: root
      MYSQL_PASSWORD: abc
      MYSQL_ROOT_PASSWORD: abc
    volumes:
    - .dbdata:/var/lib/mysql
    ports:
    - 33066:3306
    networks:
    - app
networks: 
  app:  